### ISSUE TITLE
Dead letters on subscription.close()

### ISSUE THREAD

**Issue by jknight12882** [SpinGo/op-rabbit#50] opened 2015-12-16 01:34 UTC
Using op-rabbit 2.0-M2, Akka 2.4.1

```
2015-12-16 01:31:09,591 [xxx-akka.actor.default-dispatcher-5] INFO  akka.actor.LocalActorRef - Message [com.thenewmotion.akka.rabbitmq.AmqpShutdownSignal] from Actor[akka://xxx/user/$a/connection/$a#-1532455610] to Actor[akka://xxx/user/$a/connection/$a#-1532455610] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

**Comment by timcharper** [comment] 2016-01-10 21:20
Sigh. Not sure if it's possible to avoid every instance of dead letters; I think it's quite possible that this one is caused by the Akka-RabbitMQ library op-rabbit uses.

**Comment by timcharper** [comment] 2016-09-04 21:16
Closing; this is benign and it's too hard to eliminate all dead letters.

**Closed as completed by timcharper** 2016-09-04 21:16 UTC
