### ISSUE TITLE
Release for Scala 2.12 series

### ISSUE THREAD

**Issue by danslapman** [SpinGo/op-rabbit#105] opened 2016-12-15 14:05 UTC
subj.

**Comment by timcharper** [comment] 2017-01-15 22:30
This is in progress; I have a branch, [upgrade-akka-rabbitmq-3](https://github.com/SpinGo/op-rabbit/tree/upgrade-akka-rabbitmq-3), which targets `2.12.1` and uses `akka-rabbitmq` `3.0.0`.

This needs to be resolved before we can release it:

- [x] https://github.com/timcharper/acked-stream 2.12.1 release
- [x] resolve [channel recovery regression](https://github.com/NewMotion/akka-rabbitmq/issues/39) in akka-rabbitmq.

**Comment by haggy** [comment] 2017-01-26 13:05
It looks like both issues have been resolved (2nd issue is unchecked but the fix has been merged). Any status update on the 2.12 build? We use op-rabbit heavily (like it a lot too!) and are currently blocked by it for the upgrade to scala 2.12 ourselves.

**Comment by DStranger** [comment] 2017-03-08 14:52
@timcharper as @haggy pointed out already, `akka-rabbitmq` but has been fixed and released. Is it possible to release `op-rabbit` for 2.12 as well?

**Comment by kiequoo** [comment] 2017-03-16 09:39
Hi @timcharper, it would be great if you could release this library for Scala 2.12!

**Comment by timcharper** [comment] 2017-03-21 05:32
Done!

`2.0.0-rc1`

The tests all pass and I had to update a bunch of dependencies. If everything looks good, I'll bump it to `2.0.0`.

**Closed as completed by timcharper** 2017-03-21 05:32 UTC

**Comment by haggy** [comment] 2017-04-29 14:15
@timcharper I see that there's still only a release candidate. Is this going to get promoted to `2.0.0` soon?

**Comment by timcharper** [comment] 2017-04-30 22:09
Nobody has reported any serious issues with it; what do you think ?

**Comment by haggy** [comment] 2017-05-01 14:37
It's been working fine for me. Just switched to RC1 last week, all tests pass and everything seems to run fine!

**Comment by DStranger** [comment] 2017-07-19 07:45
@timcharper are you planning on releasing 2.0.0?

**Comment by timcharper** [comment] 2017-07-20 15:31
It is released! :)

**Comment by haggy** [comment] 2017-07-20 15:54
nice ty @timcharper!!

**Comment by nikitapecasa** [comment] 2017-07-20 16:28
I'm not able to find version 2.0.0, only 2.0.0-rc1:
https://mvnrepository.com/artifact/com.spingo/op-rabbit-core_2.12/2.0.0-rc1 
and 
https://oss.sonatype.org/service/local/repositories/releases/content/com/spingo/op-rabbit-core_2.12/2.0.0-rc1/

Any advice?)

**Comment by timcharper** [comment] 2017-07-20 17:08
ah, 💩 , I forgot to run the release command

**Comment by johannegger** [comment] 2017-09-28 10:02
hi! 
is 2.0.0 really released for scala 2.12? I can't resolve it.

**Comment by timcharper** [comment] 2017-10-07 20:35
http://repo1.maven.org/maven2/com/spingo/op-rabbit_2.12/2.0.0/
